// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package iface

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of WithInterface.
func (in *WithInterface) DeepCopy() *WithInterface {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *WithInterface) deepcopy(v dc.Visited) *WithInterface {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*WithInterface)
	}
	out := new(WithInterface)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of InterfaceSlice.
func (in *InterfaceSlice) DeepCopy() *InterfaceSlice {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *InterfaceSlice) deepcopy(v dc.Visited) *InterfaceSlice {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*InterfaceSlice)
	}
	out := new(InterfaceSlice)
	v[in] = out
	*out = *in
	out.Items = dc.CopySlice(in.Items)
	return out
}

// DeepCopy returns a deep copy of InterfaceMap.
func (in *InterfaceMap) DeepCopy() *InterfaceMap {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *InterfaceMap) deepcopy(v dc.Visited) *InterfaceMap {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*InterfaceMap)
	}
	out := new(InterfaceMap)
	v[in] = out
	*out = *in
	out.Values = dc.CopyMap(v, in.Values)
	return out
}

// DeepCopy returns a deep copy of NestedInterface.
func (in *NestedInterface) DeepCopy() *NestedInterface {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *NestedInterface) deepcopy(v dc.Visited) *NestedInterface {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*NestedInterface)
	}
	out := new(NestedInterface)
	v[in] = out
	*out = *in
	out.Meta = dc.CopyMap(v, in.Meta)
	out.Tags = dc.CopySlice(in.Tags)
	return out
}
