// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package generator

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of Options.
func (in *Options) DeepCopy() *Options {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Options) deepcopy(v dc.Visited) *Options {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Options)
	}
	out := new(Options)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of genState.
func (in *genState) DeepCopy() *genState {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *genState) deepcopy(v dc.Visited) *genState {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*genState)
	}
	out := new(genState)
	v[in] = out
	*out = *in
	out.imports = dc.CopyMap(v, in.imports)
	return out
}
