package generator

import (
	"fmt"
	"github.com/451008604/deepcopy-gen/types"
	"go/parser"
	"go/token"
	"path/filepath"
	"sort"
	"strings"
)

const helperImport = "github.com/451008604/deepcopy-gen/deepcopy"

// Options configures code generation behavior.
type Options struct {
	// NoReflect skips interface{} fields that require reflect-based deep copy.
	// When enabled, interface{} fields are not copied (shallow copy via *out = *in).
	NoReflect bool
}

// Generate produces the structinfo.go file content for a given package.
func Generate(pkg types.PackageInfo) (string, error) {
	return GenerateWithOptions(pkg, Options{})
}

// GenerateWithOptions produces the structinfo.go file content with custom options.
func GenerateWithOptions(pkg types.PackageInfo, opts Options) (string, error) {
	g := &genState{
		pkgName:   pkg.Name,
		imports:   make(map[string]bool),
		noReflect: opts.NoReflect,
	}

	var methods []string
	for _, s := range pkg.Structs {
		methods = append(methods, g.genDeepCopy(s))
	}

	return g.assemble(methods), nil
}

// ValidateGenerated checks that the generated code is syntactically valid Go.
func ValidateGenerated(code string) error {
	fset := token.NewFileSet()
	_, err := parser.ParseFile(fset, "structinfo.go", code, parser.AllErrors)
	return err
}

// OutputPath returns the full path for the structinfo.go file in a package directory.
func OutputPath(pkgDir string) string {
	return filepath.Join(pkgDir, "structinfo.go")
}

type genState struct {
	pkgName     string
	imports     map[string]bool
	needsHelper bool
	noReflect   bool
}

func (g *genState) assemble(methods []string) string {
	var b strings.Builder

	b.WriteString("// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n", g.pkgName))

	if g.needsHelper {
		g.imports[helperImport] = true
	}

	if len(g.imports) > 0 {
		b.WriteString("\nimport (\n")
		paths := make([]string, 0, len(g.imports))
		for p := range g.imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			if p == helperImport {
				b.WriteString("\tdc \"github.com/451008604/deepcopy-gen/deepcopy\"\n")
			} else {
				b.WriteString(fmt.Sprintf("\t%q\n", p))
			}
		}
		b.WriteString(")\n")
	}

	for _, m := range methods {
		b.WriteString("\n")
		b.WriteString(m)
	}

	return b.String()
}

func (g *genState) genDeepCopy(s types.StructInfo) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("// DeepCopy returns a deep copy of %s.\n", s.Name))
	b.WriteString(fmt.Sprintf("func (in *%s) DeepCopy() *%s {\n", s.Name, s.Name))
	b.WriteString("\tif in == nil {\n\t\treturn nil\n\t}\n")

	if s.IsSelfReferential {
		b.WriteString("\tvisited := make(map[any]any)\n")
		b.WriteString(fmt.Sprintf("\treturn in.deepcopy(visited)\n}\n\n"))
		b.WriteString(fmt.Sprintf("func (in *%s) deepcopy(visited map[any]any) *%s {\n", s.Name, s.Name))
		b.WriteString("\tif in == nil {\n\t\treturn nil\n\t}\n")
		b.WriteString("\tif out, ok := visited[in]; ok {\n\t\treturn out.(*" + s.Name + ")\n\t}\n")
		b.WriteString(fmt.Sprintf("\tout := new(%s)\n", s.Name))
		b.WriteString("\tvisited[in] = out\n")
		b.WriteString("\t*out = *in\n")

		for _, f := range s.Fields {
			if !needsDeepCopy(f) {
				continue
			}
			line := g.genFieldCopySelfRef("out."+f.Name, "in."+f.Name, f, s.Name)
			if line != "" {
				g.needsHelper = true
				b.WriteString(line)
			}
		}
	} else {
		b.WriteString(fmt.Sprintf("\tout := new(%s)\n", s.Name))
		b.WriteString("\t*out = *in\n")

		for _, f := range s.Fields {
			if !needsDeepCopy(f) {
				continue
			}
			line := g.genFieldCopy("out."+f.Name, "in."+f.Name, f)
			if line != "" {
				g.needsHelper = true
				b.WriteString(line)
			}
		}
	}

	b.WriteString("\treturn out\n}\n")

	return b.String()
}

func needsDeepCopy(f types.FieldInfo) bool {
	if f.IsEmbedded && f.PackageName != "" {
		return true
	}
	switch f.Category {
	case types.TypePointer, types.TypeSlice, types.TypeMap, types.TypeArray, types.TypeInterface:
		return true
	default:
		return false
	}
}

func (g *genState) genFieldCopy(dst, src string, f types.FieldInfo) string {
	if f.IsEmbedded && f.PackageName != "" {
		g.imports[f.PackageName] = true
		if g.noReflect {
			return ""
		}
		return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s).(%s)\n", dst, src, f.TypeExpr)
	}
	switch f.Category {
	case types.TypePointer:
		return g.genPointerCopy(dst, src, f)
	case types.TypeSlice:
		if f.ElemCategory == types.TypeInterface {
			if g.noReflect {
				return ""
			}
			return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s).(%s)\n", dst, src, f.TypeExpr)
		}
		return g.genSliceCopy(dst, src, f)
	case types.TypeMap:
		if f.MapValueType.Category == types.TypeInterface {
			if g.noReflect {
				return ""
			}
			return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s).(%s)\n", dst, src, f.TypeExpr)
		}
		return g.genMapCopy(dst, src, f)
	case types.TypeArray:
		return g.genArrayCopy(dst, src, f)
	case types.TypeInterface:
		if g.noReflect {
			return ""
		}
		return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s).(%s)\n", dst, src, f.TypeExpr)
	default:
		return ""
	}
}

func (g *genState) genFieldCopySelfRef(dst, src string, f types.FieldInfo, structName string) string {
	if f.IsEmbedded && f.PackageName != "" {
		g.imports[f.PackageName] = true
		if g.noReflect {
			return ""
		}
		return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s).(%s)\n", dst, src, f.TypeExpr)
	}
	switch f.Category {
	case types.TypePointer:
		if f.ElemType != nil && f.ElemType.TypeName == structName {
			return fmt.Sprintf("\tif %s != nil {\n\t\t%s = %s.deepcopy(visited)\n\t}\n", src, dst, src)
		}
		return g.genPointerCopy(dst, src, f)
	case types.TypeSlice:
		if f.ElemType != nil && f.ElemType.Category == types.TypePointer &&
			f.ElemType.ElemType != nil && f.ElemType.ElemType.TypeName == structName {
			var b strings.Builder
			b.WriteString(fmt.Sprintf("\tif %s != nil {\n", src))
			b.WriteString(fmt.Sprintf("\t\t%s = make([]*%s, len(%s))\n", dst, structName, src))
			b.WriteString(fmt.Sprintf("\t\tfor i, v := range %s {\n", src))
			b.WriteString(fmt.Sprintf("\t\t\tif v != nil {\n"))
			b.WriteString(fmt.Sprintf("\t\t\t\t%s[i] = v.deepcopy(visited)\n", dst))
			b.WriteString(fmt.Sprintf("\t\t\t}\n"))
			b.WriteString("\t\t}\n")
			b.WriteString("\t}\n")
			return b.String()
		}
		if f.ElemCategory == types.TypeInterface {
			if g.noReflect {
				return ""
			}
			return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s).(%s)\n", dst, src, f.TypeExpr)
		}
		return g.genSliceCopy(dst, src, f)
	case types.TypeMap:
		if f.MapValueType != nil && f.MapValueType.Category == types.TypeInterface {
			if g.noReflect {
				return ""
			}
			return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s).(%s)\n", dst, src, f.TypeExpr)
		}
		return g.genMapCopy(dst, src, f)
	case types.TypeArray:
		return g.genArrayCopy(dst, src, f)
	case types.TypeInterface:
		if g.noReflect {
			return ""
		}
		return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s).(%s)\n", dst, src, f.TypeExpr)
	default:
		return ""
	}
}

func (g *genState) genPointerCopy(dst, src string, f types.FieldInfo) string {
	if f.ElemType.Category == types.TypePointer {
		return fmt.Sprintf("\t%s = dc.CopyDoublePtr(%s)\n", dst, src)
	}
	return fmt.Sprintf("\t%s = dc.CopyPtr(%s)\n", dst, src)
}

func (g *genState) genSliceCopy(dst, src string, f types.FieldInfo) string {
	if f.ElemCategory == types.TypeInterface {
		return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s)\n", dst, src)
	}
	switch f.ElemCategory {
	case types.TypeBasic, types.TypeStruct:
		return fmt.Sprintf("\t%s = dc.CopySlice(%s)\n", dst, src)

	case types.TypePointer:
		return fmt.Sprintf("\t%s = dc.CopySlicePtr(%s)\n", dst, src)

	case types.TypeSlice:
		return fmt.Sprintf("\t%s = dc.CopySliceSlice(%s)\n", dst, src)

	case types.TypeMap:
		keyType := f.ElemType.MapKeyType.TypeExpr
		valType := f.ElemType.MapValueType.TypeExpr
		return fmt.Sprintf("\t%s = dc.CopySliceMap[%s, %s](%s)\n", dst, keyType, valType, src)

	default:
		return fmt.Sprintf("\t%s = dc.CopySlice(%s)\n", dst, src)
	}
}

func (g *genState) genArrayCopy(dst, src string, f types.FieldInfo) string {
	switch f.ElemCategory {
	case types.TypeBasic:
		// *out = *in already copies basic-element arrays correctly.
		return ""

	case types.TypePointer:
		innerType := f.ElemType.ElemType.TypeExpr
		if f.ElemType.ElemType.PackageName != "" {
			g.imports[f.ElemType.ElemType.PackageName] = true
		}
		var b strings.Builder
		iterVar := "i"
		b.WriteString(fmt.Sprintf("\tfor %s := range %s {\n", iterVar, src))
		b.WriteString(fmt.Sprintf("\t\tif %s[%s] != nil {\n", src, iterVar))
		b.WriteString(fmt.Sprintf("\t\t\t%s[%s] = new(%s)\n", dst, iterVar, innerType))
		b.WriteString(fmt.Sprintf("\t\t\t*%s[%s] = *%s[%s]\n", dst, iterVar, src, iterVar))
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		return b.String()

	case types.TypeStruct:
		if f.ElemType != nil && f.ElemType.Category == types.TypeArray {
			var b strings.Builder
			iterVar := "i"
			b.WriteString(fmt.Sprintf("\tfor %s := range %s {\n", iterVar, src))
			b.WriteString(fmt.Sprintf("\t\t%s[%s] = %s[%s]\n", dst, iterVar, src, iterVar))
			b.WriteString("\t}\n")
			return b.String()
		}
		return ""

	default:
		var b strings.Builder
		iterVar := "i"
		b.WriteString(fmt.Sprintf("\tfor %s := range %s {\n", iterVar, src))
		b.WriteString(fmt.Sprintf("\t\t%s[%s] = %s[%s]\n", dst, iterVar, src, iterVar))
		b.WriteString("\t}\n")
		return b.String()
	}
}

func (g *genState) genMapCopy(dst, src string, f types.FieldInfo) string {
	if f.MapValueType.Category == types.TypeInterface {
		return fmt.Sprintf("\t%s = dc.DeepCopyAny(%s)\n", dst, src)
	}
	switch f.MapValueType.Category {
	case types.TypeBasic, types.TypeStruct:
		return fmt.Sprintf("\t%s = dc.CopyMap(%s)\n", dst, src)

	case types.TypePointer:
		return fmt.Sprintf("\t%s = dc.CopyMapPtr(%s)\n", dst, src)

	case types.TypeSlice:
		return fmt.Sprintf("\t%s = dc.CopyMapSlice(%s)\n", dst, src)

	default:
		return fmt.Sprintf("\t%s = dc.CopyMap(%s)\n", dst, src)
	}
}
