package generator

import (
	"fmt"
	"github.com/451008604/deepcopy-gen/types"
	"go/parser"
	"go/token"
	"path/filepath"
	"sort"
	"strings"
)

const helperImport = "github.com/451008604/deepcopy-gen/deepcopy"

type Options struct{}

func Generate(pkg types.PackageInfo) (string, error) {
	return GenerateWithOptions(pkg, Options{})
}

func GenerateWithOptions(pkg types.PackageInfo, opts Options) (string, error) {
	g := &genState{
		pkgName: pkg.Name,
		imports: make(map[string]bool),
	}

	var methods []string
	for _, s := range pkg.Structs {
		methods = append(methods, g.genDeepCopy(s))
	}

	return g.assemble(methods), nil
}

func ValidateGenerated(code string) error {
	fset := token.NewFileSet()
	_, err := parser.ParseFile(fset, "deepcopy.go", code, parser.AllErrors)
	return err
}

func OutputPath(pkgDir string) string {
	return filepath.Join(pkgDir, "deepcopy.go")
}

type genState struct {
	pkgName     string
	imports     map[string]bool
	needsHelper bool
}

func (g *genState) assemble(methods []string) string {
	var b strings.Builder

	b.WriteString("// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.\n\n")
	b.WriteString(fmt.Sprintf("package %s\n", g.pkgName))

	if g.needsHelper {
		g.imports[helperImport] = true
	}

	if len(g.imports) > 0 {
		b.WriteString("\nimport (\n")
		paths := make([]string, 0, len(g.imports))
		for p := range g.imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			if p == helperImport {
				b.WriteString("\tdc \"github.com/451008604/deepcopy-gen/deepcopy\"\n")
			} else {
				b.WriteString(fmt.Sprintf("\t%q\n", p))
			}
		}
		b.WriteString(")\n")
	}

	for _, m := range methods {
		b.WriteString("\n")
		b.WriteString(m)
	}

	return b.String()
}

func (g *genState) genDeepCopy(s types.StructInfo) string {
	var b strings.Builder

	g.needsHelper = true

	b.WriteString(fmt.Sprintf("// DeepCopy returns a deep copy of %s.\n", s.Name))
	b.WriteString(fmt.Sprintf("func (in *%s) DeepCopy() *%s {\n", s.Name, s.Name))
	b.WriteString("\tif in == nil {\n\t\treturn nil\n\t}\n")
	b.WriteString(fmt.Sprintf("\treturn in.deepcopy(make(dc.Visited))\n"))
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("func (in *%s) deepcopy(v dc.Visited) *%s {\n", s.Name, s.Name))
	b.WriteString("\tif in == nil {\n\t\treturn nil\n\t}\n")
	b.WriteString("\tif out, ok := v[in]; ok {\n\t\treturn out.(*" + s.Name + ")\n\t}\n")
	b.WriteString(fmt.Sprintf("\tout := new(%s)\n", s.Name))
	b.WriteString("\tv[in] = out\n")
	b.WriteString("\t*out = *in\n")

	for _, f := range s.Fields {
		if !needsDeepCopy(f) {
			continue
		}
		line := g.genFieldCopyVisited("out."+f.Name, "in."+f.Name, f, s.Name)
		if line != "" {
			b.WriteString(line)
		}
	}

	b.WriteString("\treturn out\n}\n")

	return b.String()
}

func needsDeepCopy(f types.FieldInfo) bool {
	if f.IsEmbedded {
		if f.Category == types.TypeInterface || f.Category == types.TypeBasic {
			return false
		}
		return true
	}
	switch f.Category {
	case types.TypePointer, types.TypeSlice, types.TypeMap, types.TypeArray, types.TypeStruct:
		return true
	default:
		return false
	}
}

func (g *genState) genFieldCopyVisited(dst, src string, f types.FieldInfo, structName string) string {
	if f.IsEmbedded {
		if f.Category == types.TypeInterface || f.Category == types.TypeBasic {
			return ""
		}
		if f.Category == types.TypePointer {
			if f.PackageName != "" {
				g.imports[f.PackageName] = true
				return fmt.Sprintf("\t%s = dc.CopyPtr(v, %s)\n", dst, src)
			}
			return fmt.Sprintf("\t%s = %s.deepcopy(v)\n", dst, src)
		}
		if f.PackageName != "" {
			return fmt.Sprintf("\t%s = *dc.CopyPtr(v, &%s)\n", dst, src)
		}
		return fmt.Sprintf("\t%s = *%s.deepcopy(v)\n", dst, src)
	}

	switch f.Category {
	case types.TypePointer:
		return g.genPointerCopyVisited(dst, src, f)
	case types.TypeSlice:
		return g.genSliceCopyVisited(dst, src, f)
	case types.TypeMap:
		return g.genMapCopyVisited(dst, src, f)
	case types.TypeArray:
		return g.genArrayCopyVisited(dst, src, f)
	default:
		return ""
	}
}

func (g *genState) genPointerCopyVisited(dst, src string, f types.FieldInfo) string {
	if f.ElemType.Category == types.TypePointer {
		return fmt.Sprintf("\t%s = dc.CopyDoublePtr(v, %s)\n", dst, src)
	}
	if f.ElemType.Category == types.TypeStruct && f.ElemType.PackageName == "" {
		return fmt.Sprintf("\t%s = %s.deepcopy(v)\n", dst, src)
	}
	return fmt.Sprintf("\t%s = dc.CopyPtr(v, %s)\n", dst, src)
}

func (g *genState) genSliceCopyVisited(dst, src string, f types.FieldInfo) string {
	switch f.ElemCategory {
	case types.TypeBasic:
		return fmt.Sprintf("\t%s = dc.CopySlice(%s)\n", dst, src)

	case types.TypeStruct:
		typeName := f.ElemType.TypeExpr
		if f.ElemType.PackageName != "" {
			g.imports[f.ElemType.PackageName] = true
			var b strings.Builder
			b.WriteString(fmt.Sprintf("\tif %s != nil {\n", src))
			b.WriteString(fmt.Sprintf("\t\t%s = make([]%s, len(%s))\n", dst, typeName, src))
			b.WriteString(fmt.Sprintf("\t\tfor i := range %s {\n", src))
			b.WriteString(fmt.Sprintf("\t\t\t%s[i] = *dc.CopyPtr(v, &%s[i])\n", dst, src))
			b.WriteString("\t\t}\n")
			b.WriteString("\t}\n")
			return b.String()
		}
		var b strings.Builder
		b.WriteString(fmt.Sprintf("\tif %s != nil {\n", src))
		b.WriteString(fmt.Sprintf("\t\t%s = make([]%s, len(%s))\n", dst, typeName, src))
		b.WriteString(fmt.Sprintf("\t\tfor i := range %s {\n", src))
		b.WriteString(fmt.Sprintf("\t\t\t%s[i] = *%s[i].deepcopy(v)\n", dst, src))
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		return b.String()

	case types.TypePointer:
		return fmt.Sprintf("\t%s = dc.CopySlicePtr(v, %s)\n", dst, src)

	case types.TypeSlice:
		return fmt.Sprintf("\t%s = dc.CopySliceSlice(v, %s)\n", dst, src)

	case types.TypeMap:
		keyType := f.ElemType.MapKeyType.TypeExpr
		valType := f.ElemType.MapValueType.TypeExpr
		return fmt.Sprintf("\t%s = dc.CopySliceMap[%s, %s](v, %s)\n", dst, keyType, valType, src)

	default:
		return fmt.Sprintf("\t%s = dc.CopySlice(%s)\n", dst, src)
	}
}

func (g *genState) genArrayCopyVisited(dst, src string, f types.FieldInfo) string {
	switch f.ElemCategory {
	case types.TypeBasic:
		return ""

	case types.TypePointer:
		innerType := f.ElemType.ElemType.TypeExpr
		if f.ElemType.ElemType.PackageName != "" {
			g.imports[f.ElemType.ElemType.PackageName] = true
		}
		var b strings.Builder
		iterVar := "i"
		b.WriteString(fmt.Sprintf("\tfor %s := range %s {\n", iterVar, src))
		b.WriteString(fmt.Sprintf("\t\tif %s[%s] != nil {\n", src, iterVar))
		b.WriteString(fmt.Sprintf("\t\t\t%s[%s] = new(%s)\n", dst, iterVar, innerType))
		b.WriteString(fmt.Sprintf("\t\t\t*%s[%s] = *%s[%s]\n", dst, iterVar, src, iterVar))
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")
		return b.String()

	case types.TypeStruct:
		if f.ElemType != nil && f.ElemType.Category == types.TypeArray {
			var b strings.Builder
			iterVar := "i"
			b.WriteString(fmt.Sprintf("\tfor %s := range %s {\n", iterVar, src))
			b.WriteString(fmt.Sprintf("\t\t%s[%s] = %s[%s]\n", dst, iterVar, src, iterVar))
			b.WriteString("\t}\n")
			return b.String()
		}
		if f.ElemType.PackageName != "" {
			g.imports[f.ElemType.PackageName] = true
			var b strings.Builder
			b.WriteString(fmt.Sprintf("\tfor i := range %s {\n", src))
			b.WriteString(fmt.Sprintf("\t\t%s[i] = *dc.CopyPtr(v, &%s[i])\n", dst, src))
			b.WriteString("\t}\n")
			return b.String()
		}
		var b strings.Builder
		b.WriteString(fmt.Sprintf("\tfor i := range %s {\n", src))
		b.WriteString(fmt.Sprintf("\t\t%s[i] = *%s[i].deepcopy(v)\n", dst, src))
		b.WriteString("\t}\n")
		return b.String()

	default:
		var b strings.Builder
		iterVar := "i"
		b.WriteString(fmt.Sprintf("\tfor %s := range %s {\n", iterVar, src))
		b.WriteString(fmt.Sprintf("\t\t%s[%s] = %s[%s]\n", dst, iterVar, src, iterVar))
		b.WriteString("\t}\n")
		return b.String()
	}
}

func (g *genState) genMapCopyVisited(dst, src string, f types.FieldInfo) string {
	switch f.MapValueType.Category {
	case types.TypeBasic, types.TypeStruct:
		return fmt.Sprintf("\t%s = dc.CopyMap(v, %s)\n", dst, src)

	case types.TypePointer:
		return fmt.Sprintf("\t%s = dc.CopyMapPtr(v, %s)\n", dst, src)

	case types.TypeSlice:
		return fmt.Sprintf("\t%s = dc.CopyMapSlice(v, %s)\n", dst, src)

	default:
		return fmt.Sprintf("\t%s = dc.CopyMap(v, %s)\n", dst, src)
	}
}
