// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package types

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of FieldInfo.
func (in *FieldInfo) DeepCopy() *FieldInfo {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *FieldInfo) deepcopy(v dc.Visited) *FieldInfo {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*FieldInfo)
	}
	out := new(FieldInfo)
	v[in] = out
	*out = *in
	out.ElemType = in.ElemType.deepcopy(v)
	out.MapKeyType = in.MapKeyType.deepcopy(v)
	out.MapValueType = in.MapValueType.deepcopy(v)
	return out
}

// DeepCopy returns a deep copy of StructInfo.
func (in *StructInfo) DeepCopy() *StructInfo {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *StructInfo) deepcopy(v dc.Visited) *StructInfo {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*StructInfo)
	}
	out := new(StructInfo)
	v[in] = out
	*out = *in
	if in.Fields != nil {
		out.Fields = make([]FieldInfo, len(in.Fields))
		for i := range in.Fields {
			out.Fields[i] = *in.Fields[i].deepcopy(v)
		}
	}
	return out
}

// DeepCopy returns a deep copy of PackageInfo.
func (in *PackageInfo) DeepCopy() *PackageInfo {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *PackageInfo) deepcopy(v dc.Visited) *PackageInfo {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*PackageInfo)
	}
	out := new(PackageInfo)
	v[in] = out
	*out = *in
	if in.Structs != nil {
		out.Structs = make([]StructInfo, len(in.Structs))
		for i := range in.Structs {
			out.Structs[i] = *in.Structs[i].deepcopy(v)
		}
	}
	out.GoFiles = dc.CopySlice(in.GoFiles)
	return out
}
