// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package embedded

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of Base.
func (in *Base) DeepCopy() *Base {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Base) deepcopy(v dc.Visited) *Base {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Base)
	}
	out := new(Base)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of Timestamped.
func (in *Timestamped) DeepCopy() *Timestamped {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Timestamped) deepcopy(v dc.Visited) *Timestamped {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Timestamped)
	}
	out := new(Timestamped)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of WithEmbedded.
func (in *WithEmbedded) DeepCopy() *WithEmbedded {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *WithEmbedded) deepcopy(v dc.Visited) *WithEmbedded {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*WithEmbedded)
	}
	out := new(WithEmbedded)
	v[in] = out
	*out = *in
	out.Base = *in.Base.deepcopy(v)
	out.Timestamped = *in.Timestamped.deepcopy(v)
	return out
}

// DeepCopy returns a deep copy of WithEmbeddedPointer.
func (in *WithEmbeddedPointer) DeepCopy() *WithEmbeddedPointer {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *WithEmbeddedPointer) deepcopy(v dc.Visited) *WithEmbeddedPointer {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*WithEmbeddedPointer)
	}
	out := new(WithEmbeddedPointer)
	v[in] = out
	*out = *in
	out.Base = in.Base.deepcopy(v)
	return out
}
