// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package edgecase

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of WithInterface.
func (in *WithInterface) DeepCopy() *WithInterface {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *WithInterface) deepcopy(v dc.Visited) *WithInterface {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*WithInterface)
	}
	out := new(WithInterface)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of WithChannel.
func (in *WithChannel) DeepCopy() *WithChannel {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *WithChannel) deepcopy(v dc.Visited) *WithChannel {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*WithChannel)
	}
	out := new(WithChannel)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of withUnexported.
func (in *withUnexported) DeepCopy() *withUnexported {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *withUnexported) deepcopy(v dc.Visited) *withUnexported {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*withUnexported)
	}
	out := new(withUnexported)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of MultiName.
func (in *MultiName) DeepCopy() *MultiName {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *MultiName) deepcopy(v dc.Visited) *MultiName {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*MultiName)
	}
	out := new(MultiName)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of ArrayOfPointers.
func (in *ArrayOfPointers) DeepCopy() *ArrayOfPointers {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *ArrayOfPointers) deepcopy(v dc.Visited) *ArrayOfPointers {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*ArrayOfPointers)
	}
	out := new(ArrayOfPointers)
	v[in] = out
	*out = *in
	for i := range in.Ptrs {
		if in.Ptrs[i] != nil {
			out.Ptrs[i] = new(int)
			*out.Ptrs[i] = *in.Ptrs[i]
		}
	}
	return out
}

// DeepCopy returns a deep copy of SliceOfMaps.
func (in *SliceOfMaps) DeepCopy() *SliceOfMaps {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *SliceOfMaps) deepcopy(v dc.Visited) *SliceOfMaps {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*SliceOfMaps)
	}
	out := new(SliceOfMaps)
	v[in] = out
	*out = *in
	out.Maps = dc.CopySliceMap[string, int](v, in.Maps)
	return out
}
