// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package multifile

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of Foo.
func (in *Foo) DeepCopy() *Foo {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Foo) deepcopy(v dc.Visited) *Foo {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Foo)
	}
	out := new(Foo)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of Bar.
func (in *Bar) DeepCopy() *Bar {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Bar) deepcopy(v dc.Visited) *Bar {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Bar)
	}
	out := new(Bar)
	v[in] = out
	*out = *in
	return out
}
