// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package empty

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of Empty.
func (in *Empty) DeepCopy() *Empty {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Empty) deepcopy(v dc.Visited) *Empty {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Empty)
	}
	out := new(Empty)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of Marker.
func (in *Marker) DeepCopy() *Marker {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Marker) deepcopy(v dc.Visited) *Marker {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Marker)
	}
	out := new(Marker)
	v[in] = out
	*out = *in
	return out
}
