// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package selector

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of Event.
func (in *Event) DeepCopy() *Event {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Event) deepcopy(v dc.Visited) *Event {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Event)
	}
	out := new(Event)
	v[in] = out
	*out = *in
	out.UpdatedAt = dc.CopyPtr(v, in.UpdatedAt)
	return out
}
