// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package selfref

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of TreeNode.
func (in *TreeNode) DeepCopy() *TreeNode {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *TreeNode) deepcopy(v dc.Visited) *TreeNode {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*TreeNode)
	}
	out := new(TreeNode)
	v[in] = out
	*out = *in
	out.Children = dc.CopySlicePtr(v, in.Children)
	out.Parent = in.Parent.deepcopy(v)
	return out
}

// DeepCopy returns a deep copy of GraphNode.
func (in *GraphNode) DeepCopy() *GraphNode {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *GraphNode) deepcopy(v dc.Visited) *GraphNode {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*GraphNode)
	}
	out := new(GraphNode)
	v[in] = out
	*out = *in
	out.Neighbors = dc.CopySlicePtr(v, in.Neighbors)
	out.Metadata = dc.CopyMap(v, in.Metadata)
	return out
}

// DeepCopy returns a deep copy of LinkedNode.
func (in *LinkedNode) DeepCopy() *LinkedNode {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *LinkedNode) deepcopy(v dc.Visited) *LinkedNode {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*LinkedNode)
	}
	out := new(LinkedNode)
	v[in] = out
	*out = *in
	out.Next = in.Next.deepcopy(v)
	return out
}

// DeepCopy returns a deep copy of TreeWithMap.
func (in *TreeWithMap) DeepCopy() *TreeWithMap {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *TreeWithMap) deepcopy(v dc.Visited) *TreeWithMap {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*TreeWithMap)
	}
	out := new(TreeWithMap)
	v[in] = out
	*out = *in
	out.Children = dc.CopyMapPtr(v, in.Children)
	return out
}
