// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package simple

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of Point.
func (in *Point) DeepCopy() *Point {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Point) deepcopy(v dc.Visited) *Point {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Point)
	}
	out := new(Point)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of Person.
func (in *Person) DeepCopy() *Person {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Person) deepcopy(v dc.Visited) *Person {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Person)
	}
	out := new(Person)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Config) deepcopy(v dc.Visited) *Config {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Config)
	}
	out := new(Config)
	v[in] = out
	*out = *in
	return out
}
