// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package crosspkg

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
	"github.com/451008604/deepcopy-gen/testdata/external"
)

// DeepCopy returns a deep copy of Player.
func (in *Player) DeepCopy() *Player {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Player) deepcopy(v dc.Visited) *Player {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Player)
	}
	out := new(Player)
	v[in] = out
	*out = *in
	out.AccountInfo = *dc.CopyPtr(v, &in.AccountInfo)
	return out
}

// DeepCopy returns a deep copy of Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Team) deepcopy(v dc.Visited) *Team {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Team)
	}
	out := new(Team)
	v[in] = out
	*out = *in
	if in.Players != nil {
		out.Players = make([]Player, len(in.Players))
		for i := range in.Players {
			out.Players[i] = *in.Players[i].deepcopy(v)
		}
	}
	out.Captain = in.Captain.deepcopy(v)
	return out
}

// DeepCopy returns a deep copy of GameSession.
func (in *GameSession) DeepCopy() *GameSession {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *GameSession) deepcopy(v dc.Visited) *GameSession {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*GameSession)
	}
	out := new(GameSession)
	v[in] = out
	*out = *in
	out.Player = in.Player.deepcopy(v)
	out.Team = in.Team.deepcopy(v)
	out.History = dc.CopySliceMap[string, int](v, in.History)
	return out
}

// DeepCopy returns a deep copy of PlayerWithExtra.
func (in *PlayerWithExtra) DeepCopy() *PlayerWithExtra {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *PlayerWithExtra) deepcopy(v dc.Visited) *PlayerWithExtra {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*PlayerWithExtra)
	}
	out := new(PlayerWithExtra)
	v[in] = out
	*out = *in
	out.AccountInfo = *dc.CopyPtr(v, &in.AccountInfo)
	out.AccountExtra = *dc.CopyPtr(v, &in.AccountExtra)
	return out
}

// DeepCopy returns a deep copy of PointerEmbed.
func (in *PointerEmbed) DeepCopy() *PointerEmbed {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *PointerEmbed) deepcopy(v dc.Visited) *PointerEmbed {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*PointerEmbed)
	}
	out := new(PointerEmbed)
	v[in] = out
	*out = *in
	out.AccountInfo = in.AccountInfo.deepcopy(v)
	return out
}

// DeepCopy returns a deep copy of SliceOfExternal.
func (in *SliceOfExternal) DeepCopy() *SliceOfExternal {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *SliceOfExternal) deepcopy(v dc.Visited) *SliceOfExternal {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*SliceOfExternal)
	}
	out := new(SliceOfExternal)
	v[in] = out
	*out = *in
	if in.Items != nil {
		out.Items = make([]external.AccountInfo, len(in.Items))
		for i := range in.Items {
			out.Items[i] = *dc.CopyPtr(v, &in.Items[i])
		}
	}
	return out
}

// DeepCopy returns a deep copy of MapOfExternal.
func (in *MapOfExternal) DeepCopy() *MapOfExternal {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *MapOfExternal) deepcopy(v dc.Visited) *MapOfExternal {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*MapOfExternal)
	}
	out := new(MapOfExternal)
	v[in] = out
	*out = *in
	out.Items = dc.CopyMapPtr(v, in.Items)
	return out
}

// DeepCopy returns a deep copy of SliceOfExternalPtr.
func (in *SliceOfExternalPtr) DeepCopy() *SliceOfExternalPtr {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *SliceOfExternalPtr) deepcopy(v dc.Visited) *SliceOfExternalPtr {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*SliceOfExternalPtr)
	}
	out := new(SliceOfExternalPtr)
	v[in] = out
	*out = *in
	out.Items = dc.CopySlicePtr(v, in.Items)
	return out
}

// DeepCopy returns a deep copy of MultiExternalEmbed.
func (in *MultiExternalEmbed) DeepCopy() *MultiExternalEmbed {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *MultiExternalEmbed) deepcopy(v dc.Visited) *MultiExternalEmbed {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*MultiExternalEmbed)
	}
	out := new(MultiExternalEmbed)
	v[in] = out
	*out = *in
	out.AccountInfo = *dc.CopyPtr(v, &in.AccountInfo)
	out.GameItem = *dc.CopyPtr(v, &in.GameItem)
	out.Character = *dc.CopyPtr(v, &in.Character)
	return out
}

// DeepCopy returns a deep copy of ExternalWithPointerToExternal.
func (in *ExternalWithPointerToExternal) DeepCopy() *ExternalWithPointerToExternal {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *ExternalWithPointerToExternal) deepcopy(v dc.Visited) *ExternalWithPointerToExternal {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*ExternalWithPointerToExternal)
	}
	out := new(ExternalWithPointerToExternal)
	v[in] = out
	*out = *in
	out.Owner = dc.CopyPtr(v, in.Owner)
	out.Items = dc.CopySlicePtr(v, in.Items)
	return out
}

// DeepCopy returns a deep copy of ExternalWithSliceOfExternal.
func (in *ExternalWithSliceOfExternal) DeepCopy() *ExternalWithSliceOfExternal {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *ExternalWithSliceOfExternal) deepcopy(v dc.Visited) *ExternalWithSliceOfExternal {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*ExternalWithSliceOfExternal)
	}
	out := new(ExternalWithSliceOfExternal)
	v[in] = out
	*out = *in
	if in.Inventory != nil {
		out.Inventory = make([]external.GameItem, len(in.Inventory))
		for i := range in.Inventory {
			out.Inventory[i] = *dc.CopyPtr(v, &in.Inventory[i])
		}
	}
	out.History = dc.CopySlicePtr(v, in.History)
	return out
}

// DeepCopy returns a deep copy of ExternalWithMapOfExternal.
func (in *ExternalWithMapOfExternal) DeepCopy() *ExternalWithMapOfExternal {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *ExternalWithMapOfExternal) deepcopy(v dc.Visited) *ExternalWithMapOfExternal {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*ExternalWithMapOfExternal)
	}
	out := new(ExternalWithMapOfExternal)
	v[in] = out
	*out = *in
	out.Inventory = dc.CopyMap(v, in.Inventory)
	out.LastActive = dc.CopyMapPtr(v, in.LastActive)
	return out
}

// DeepCopy returns a deep copy of NestedExternal.
func (in *NestedExternal) DeepCopy() *NestedExternal {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *NestedExternal) deepcopy(v dc.Visited) *NestedExternal {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*NestedExternal)
	}
	out := new(NestedExternal)
	v[in] = out
	*out = *in
	out.GameState = *dc.CopyPtr(v, &in.GameState)
	return out
}

// DeepCopy returns a deep copy of ExternalWithLocalSlice.
func (in *ExternalWithLocalSlice) DeepCopy() *ExternalWithLocalSlice {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *ExternalWithLocalSlice) deepcopy(v dc.Visited) *ExternalWithLocalSlice {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*ExternalWithLocalSlice)
	}
	out := new(ExternalWithLocalSlice)
	v[in] = out
	*out = *in
	if in.Friends != nil {
		out.Friends = make([]Player, len(in.Friends))
		for i := range in.Friends {
			out.Friends[i] = *in.Friends[i].deepcopy(v)
		}
	}
	if in.Items != nil {
		out.Items = make([]external.GameItem, len(in.Items))
		for i := range in.Items {
			out.Items[i] = *dc.CopyPtr(v, &in.Items[i])
		}
	}
	return out
}
