// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package nested

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of Address.
func (in *Address) DeepCopy() *Address {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Address) deepcopy(v dc.Visited) *Address {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Address)
	}
	out := new(Address)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of Employee.
func (in *Employee) DeepCopy() *Employee {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Employee) deepcopy(v dc.Visited) *Employee {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Employee)
	}
	out := new(Employee)
	v[in] = out
	*out = *in
	out.WorkAddr = in.WorkAddr.deepcopy(v)
	out.Emails = dc.CopySlice(in.Emails)
	out.Manager = in.Manager.deepcopy(v)
	out.Tags = dc.CopyMap(v, in.Tags)
	return out
}

// DeepCopy returns a deep copy of Department.
func (in *Department) DeepCopy() *Department {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Department) deepcopy(v dc.Visited) *Department {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Department)
	}
	out := new(Department)
	v[in] = out
	*out = *in
	out.Head = in.Head.deepcopy(v)
	if in.Members != nil {
		out.Members = make([]Employee, len(in.Members))
		for i := range in.Members {
			out.Members[i] = *in.Members[i].deepcopy(v)
		}
	}
	out.Locations = dc.CopySlicePtr(v, in.Locations)
	out.Budget = dc.CopyMap(v, in.Budget)
	return out
}

// DeepCopy returns a deep copy of Node.
func (in *Node) DeepCopy() *Node {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Node) deepcopy(v dc.Visited) *Node {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Node)
	}
	out := new(Node)
	v[in] = out
	*out = *in
	out.Children = dc.CopySlicePtr(v, in.Children)
	out.Parent = in.Parent.deepcopy(v)
	out.Metadata = dc.CopyMap(v, in.Metadata)
	return out
}
