// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package gamecore

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of Position.
func (in *Position) DeepCopy() *Position {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Position) deepcopy(v dc.Visited) *Position {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Position)
	}
	out := new(Position)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of Character.
func (in *Character) DeepCopy() *Character {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Character) deepcopy(v dc.Visited) *Character {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Character)
	}
	out := new(Character)
	v[in] = out
	*out = *in
	return out
}

// DeepCopy returns a deep copy of Inventory.
func (in *Inventory) DeepCopy() *Inventory {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Inventory) deepcopy(v dc.Visited) *Inventory {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Inventory)
	}
	out := new(Inventory)
	v[in] = out
	*out = *in
	out.Slots = dc.CopySlicePtr(v, in.Slots)
	return out
}

// DeepCopy returns a deep copy of Item.
func (in *Item) DeepCopy() *Item {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Item) deepcopy(v dc.Visited) *Item {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Item)
	}
	out := new(Item)
	v[in] = out
	*out = *in
	return out
}
