// Code generated by github.com/451008604/deepcopy-gen. DO NOT EDIT.

package complex

import (
	dc "github.com/451008604/deepcopy-gen/deepcopy"
)

// DeepCopy returns a deep copy of WithPointer.
func (in *WithPointer) DeepCopy() *WithPointer {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *WithPointer) deepcopy(v dc.Visited) *WithPointer {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*WithPointer)
	}
	out := new(WithPointer)
	v[in] = out
	*out = *in
	out.Name = dc.CopyPtr(v, in.Name)
	out.Value = dc.CopyPtr(v, in.Value)
	out.Data = dc.CopyPtr(v, in.Data)
	out.Ref = dc.CopyDoublePtr(v, in.Ref)
	return out
}

// DeepCopy returns a deep copy of WithSlice.
func (in *WithSlice) DeepCopy() *WithSlice {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *WithSlice) deepcopy(v dc.Visited) *WithSlice {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*WithSlice)
	}
	out := new(WithSlice)
	v[in] = out
	*out = *in
	out.Names = dc.CopySlice(in.Names)
	out.Numbers = dc.CopySlice(in.Numbers)
	out.Matrix = dc.CopySliceSlice(v, in.Matrix)
	out.Ptrs = dc.CopySlicePtr(v, in.Ptrs)
	return out
}

// DeepCopy returns a deep copy of WithMap.
func (in *WithMap) DeepCopy() *WithMap {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *WithMap) deepcopy(v dc.Visited) *WithMap {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*WithMap)
	}
	out := new(WithMap)
	v[in] = out
	*out = *in
	out.Labels = dc.CopyMap(v, in.Labels)
	out.Scores = dc.CopyMap(v, in.Scores)
	out.Nested = dc.CopyMapSlice(v, in.Nested)
	out.PtrMap = dc.CopyMapPtr(v, in.PtrMap)
	out.IntKeyMap = dc.CopyMap(v, in.IntKeyMap)
	return out
}

// DeepCopy returns a deep copy of WithArray.
func (in *WithArray) DeepCopy() *WithArray {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *WithArray) deepcopy(v dc.Visited) *WithArray {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*WithArray)
	}
	out := new(WithArray)
	v[in] = out
	*out = *in
	for i := range in.Matrix {
		out.Matrix[i] = in.Matrix[i]
	}
	return out
}

// DeepCopy returns a deep copy of Mixed.
func (in *Mixed) DeepCopy() *Mixed {
	if in == nil {
		return nil
	}
	return in.deepcopy(make(dc.Visited))
}

func (in *Mixed) deepcopy(v dc.Visited) *Mixed {
	if in == nil {
		return nil
	}
	if out, ok := v[in]; ok {
		return out.(*Mixed)
	}
	out := new(Mixed)
	v[in] = out
	*out = *in
	out.Name = dc.CopyPtr(v, in.Name)
	out.Tags = dc.CopySlice(in.Tags)
	out.Metadata = dc.CopyMap(v, in.Metadata)
	out.Scores = dc.CopySlicePtr(v, in.Scores)
	return out
}
